### PR TITLE
Rename wrap1 to world with some minor fixes

### PR DESCRIPTION
**Pull request by r9y9**
This PR basically proposes renaming `wrap1` to `world`. This work was done when I was going to use this package in my own python project.

Actually this PR contains several different fixes (renaming, adding simple tests, travis CI, setup.py minor fix etc), so if you have some problem with this I can create a smaller PR.

### CODE REVIEW

**Comment by kastnerkyle** [comment]
This looks great! Thanks

**Comment by r9y9** [comment]
Thanks for merging this! 

```md
[![Build Status](https://travis-ci.org/r9y9/world.py.svg?branch=dev)](https://travis-ci.org/r9y9/world.py)
```

Apparently this should be changed to:
```md
[![Build Status](https://travis-ci.org/jimsotelo/world.py.svg?branch=master)](https://travis-ci.org/jimsotelo/world.py)
```

Because I don't have right to enable Travis CI for `jimsotelo/world.py`, could anyone switch it on and fix the badge URL?

**Comment by kastnerkyle** [comment]
We added you as a collaborator. If you don't have time I can try to take a
look later in the week. Thanks for all your work so far!

**Comment by r9y9** [comment]
Thanks for adding me as a collaborator. 

I was trying to enable Travis but I couldn't do it. I wonder the administrator can only do. When you get a change, would you try to do it? @jimsotelo

**Comment by jimsotelo** [comment]
Hey,
Thanks for everything :)

I've enabled Travis CI and added the badge. However, something seems to be not working.

**Comment by r9y9** [comment]
Thanks! I see travis says `build passing`. It seems to be working now, is it?

**Comment by jimsotelo** [comment]
Yes. I checked later and it was working. Probably it is that it just took some time to compile.

**Comment by r9y9** [comment]
I see. Thanks, too!

**Pull request merged**
